// App-level constants, shared state, and DOM references.
const DB_NAME = "ragint-pad-db";
const DB_VERSION = 1;
const SNAPSHOT_STORE = "hall_snapshots";
const AUDIO_CACHE = "ragint-pad-audio-v1";
const IMAGE_CACHE = "ragint-pad-image-v1";
const PRODUCT_PLAY_COUNT_STORAGE_KEY = "ragint-pad-demo-play-counts-v1";
const DEMO_COLUMNS_STORAGE_KEY = "ragint-pad-demo-columns-v1";
const STATION_SLOT_STORAGE_KEY = "ragint-pad-demo-station-slots-v1";
const REQUEST_TIMEOUT_MS = 12000;
const DEFAULT_MODE = "demo";
const DEFAULT_DEMO_COLUMNS = 2;
const MIN_DEMO_COLUMNS = 1;
const MAX_DEMO_COLUMNS = 4;
const STATION_SLOT_KEYS = Object.freeze(["display_slot_1", "display_slot_2"]);
const LEGACY_STATION_SLOT_KEY_MAP = Object.freeze({
  station_a: "display_slot_1",
  station_b: "display_slot_2",
});
const DEFAULT_DEMO_LEFT_TAB = "display_slot_1";
const DEFAULT_DEMO_RIGHT_TAB = "product";
const RECORDING_OPTIONS_LIMIT = 100;

const TEXT = Object.freeze({
  loading: "正在加载当前展厅和产品列表...",
  loadFailed: "在线加载失败",
  offlineNotReady: "离线资源未就绪",
  offlineNotReadyDetail: "当前设备尚未完成本展厅的离线同步，请先在线同步一次。",
  hallBindingNotFoundDetail: "当前 clientId 尚未绑定展厅，请先在下方切换展厅。",
  backendErrorPrefix: "后端错误：",
  backendUnknownDetail: "\u540e\u7aef\u8fd4\u56de\u4e86\u672a\u9884\u671f\u7684\u72b6\u6001\u3002",
  unboundHall: "\u672a\u7ed1\u5b9a\u5c55\u5385",
  liveData: "实时数据",
  offlineSnapshot: "离线快照",
  noProducts: "\u5f53\u524d\u5c55\u5385\u6682\u65e0\u4ea7\u54c1\u3002",
  noSelection: "\u8bf7\u5148\u5728\u5de6\u4fa7\u9009\u62e9\u4e00\u4e2a\u4ea7\u54c1\u3002",
  noAudio: "\u8be5\u4ea7\u54c1\u6682\u65e0\u751f\u6548\u8bb2\u89e3\u97f3\u9891\u3002",
  audioPlayFailed: "\u4ea7\u54c1\u8bb2\u89e3\u97f3\u9891\u64ad\u653e\u5931\u8d25\uff0c\u8bf7\u786e\u8ba4\u8d44\u6e90\u662f\u5426\u5df2\u540c\u6b65\u3002",
  audioPreparing: "\u6b63\u5728\u51c6\u5907\u64ad\u653e...",
  audioPlay: "\u64ad\u653e\u8bb2\u89e3",
  currentAudioReady: "\u97f3\u9891\u5df2\u5c31\u7eea",
  currentAudioMissing: "\u6682\u65e0\u97f3\u9891",
  introTitle: "\u4ea7\u54c1\u8bf4\u660e",
  infoTitle: "\u4ea7\u54c1\u4fe1\u606f",
  registrationName: "\u6ce8\u518c\u8bc1\u540d\u79f0",
  registrationNumber: "\u6ce8\u518c\u8bc1\u53f7",
  effectiveDate: "\u751f\u6548\u65e5\u671f",
  company: "\u6240\u5c5e\u516c\u53f8",
  emptyField: "\u672a\u586b\u5199",
  currentAudioStatusReady: "\u8bb2\u89e3\u5df2\u5c31\u7eea",
  currentAudioStatusMissing: "\u6682\u65e0\u751f\u6548\u97f3\u9891",
  currentAudioStatusFailed: "\u64ad\u653e\u5931\u8d25",
  currentAudioStatusPreparing: "\u51c6\u5907\u64ad\u653e\u4e2d",
  currentAudioStatusPlaying: "\u64ad\u653e\u4e2d",
  notSelected: "\u672a\u9009\u62e9\u4ea7\u54c1",
  heroEyebrow: "Hall Product Explainer",
  heroSubtitle: "This device binds a hall by clientId and prioritizes that hall's offline assets.",
  refreshOnline: "\u5728\u7ebf\u5237\u65b0",
  syncOffline: "\u79bb\u7ebf\u540c\u6b65",
  gotoRagint: "\u8fdb\u5165\u8bb2\u89e3\u6a21\u5f0f",
  statClientId: "\u8bbe\u5907 clientId",
  statProductCount: "\u4ea7\u54c1\u6570",
  statNetwork: "\u7f51\u7edc",
  statOffline: "\u79bb\u7ebf\u8d44\u6e90",
  online: "\u5728\u7ebf",
  offline: "\u79bb\u7ebf",
  hallListTitle: "\u5c55\u5385\u4ea7\u54c1\u5217\u8868",
  lastSyncAt: "\u6700\u8fd1\u540c\u6b65\uff1a",
  currentPlaying: "\u5f53\u524d\u64ad\u653e",
  syncPendingInit: "\u6b63\u5728\u51c6\u5907\u5c55\u5385\u8d44\u6e90",
  syncPendingOnlineLoaded: "\u5728\u7ebf\u6570\u636e\u5df2\u52a0\u8f7d\uff0c\u6b63\u5728\u51c6\u5907\u79bb\u7ebf\u5305",
  syncPendingSyncing: "\u6b63\u5728\u540c\u6b65\u5f53\u524d\u5c55\u5385\u7684\u79bb\u7ebf\u8d44\u6e90",
  syncReadyOffline: "\u5f53\u524d\u4f7f\u7528\u79bb\u7ebf\u8d44\u6e90",
  syncReadyCountPrefix: "\u79bb\u7ebf\u8d44\u6e90\u5df2\u540c\u6b65\uff08",
  syncReadyCountSuffix: " \u6761\u97f3\u9891\uff09",
  syncDangerLoadFailed: "\u5f53\u524d\u5c55\u5385\u52a0\u8f7d\u5931\u8d25",
  syncDangerOfflineNotReady: "\u79bb\u7ebf\u8d44\u6e90\u672a\u5c31\u7eea",
  syncDangerOfflineUnsupported: "\u5f53\u524d\u6d4f\u89c8\u5668\u4e0d\u652f\u6301\u79bb\u7ebf\u7f13\u5b58",
  syncDangerOfflineInitFailed: "\u79bb\u7ebf\u7f13\u5b58\u521d\u59cb\u5316\u5931\u8d25",
  syncDangerOfflineSyncFailed: "\u79bb\u7ebf\u540c\u6b65\u5931\u8d25\uff1a",
  syncDangerOfflineUnsupportedDetail: "\u5f53\u524d\u6d4f\u89c8\u5668\u4e0d\u652f\u6301\u79bb\u7ebf\u8d44\u6e90\uff1a",
  bannerUsingOffline: "\u5f53\u524d\u6b63\u5728\u4f7f\u7528\u672c\u5730\u79bb\u7ebf\u8d44\u6e90\u3002",
  bannerOfflineReady: "\u79bb\u7ebf\u8d44\u6e90\u5df2\u51c6\u5907\u5b8c\u6210\uff0c\u65ad\u7f51\u540e\u4ecd\u53ef\u7ee7\u7eed\u64ad\u653e\u3002",
  bannerOnlineOnly: "\u5f53\u524d\u4e3a\u5728\u7ebf\u6570\u636e\u89c6\u56fe\uff0c\u79bb\u7ebf\u8d44\u6e90\u5c1a\u672a\u5b8c\u5168\u540c\u6b65\u3002",
  quickSwitchTitle: "\u5feb\u901f\u5207\u5385",
  quickSwitchHint: "\u70b9\u51fb\u6309\u94ae\u5373\u53ef\u5207\u6362\u5f53\u524d Pad \u7684 clientId \u4e0e\u5c55\u5385\u5185\u5bb9\u3002",
  modeLabel: "\u754c\u9762\u6a21\u5f0f",
  modeDemo: "\u6f14\u793a",
  modeOps: "\u8fd0\u7ef4",
  demoEyebrow: "Exhibit Playback",
  demoSubtitle: "Tap a product item to play the active narration audio.",
  demoListTitle: "Tap a product to start narration",
  demoListHint: "Keeps only the product list and playback state needed for the on-site demo.",
  demoAudienceTitle: "Product narration",
  demoAudienceHint: "Tap a product to play narration audio.",
  demoEnterOps: "Ops",
  demoStatusPlaying: "Playing",
  demoStatusPreparing: "Preparing",
  demoStatusMissing: "No audio",
});

const IMAGE_TEXT = Object.freeze({
  sectionTitle: "Product images",
  upload: "Upload image",
  uploading: "Uploading image...",
  empty: "No images uploaded for this product yet.",
  uploadHint: "Supports png, jpg, jpeg, webp, gif, bmp; uploaded images will sync to offline assets.",
  syncReadySuffix: " image(s) synced",
  uploadSuccessMiddle: " product image(s) uploaded and synced.",
  uploadSuccessSyncFailed: "Images uploaded, but offline sync failed. Please retry later.",
});
const IMAGE_FALLBACK_NOTE = "\u5f53\u524d\u672a\u4e0a\u4f20\u4ea7\u54c1\u56fe\u7247\uff0c\u6b63\u5728\u4f7f\u7528\u9ed8\u8ba4\u5c55\u793a\u56fe\u3002";
const FALLBACK_IMAGE_LOG_PREFIX = "[pad:fallback-image]";
const fallbackImageLogKeys = new Set();
const CONTROL_HOTSPOT_ACTIONS = Object.freeze({
  __control_toggle_station__: "toggle_station",
  __control_toggle_station_narration__: "toggle_station_narration",
  __control_enter_ops__: "enter_ops",
  __control_exit_app__: "exit_app",
});
const CONTROL_HOTSPOT_LABELS = Object.freeze({
  toggle_station: "站台切换",
  toggle_station_narration: "全站讲解",
  enter_ops: "运维",
  exit_app: "退出",
});

const TIMELINE_EVENT_TYPE_LABELS = Object.freeze({
  focus_switch: "切换焦点",
  highlight_on: "开启高亮",
  highlight_off: "取消高亮",
});

const HALL_PRESETS = Object.freeze([
  { clientId: "pad-a", hallId: "hall_01", hallName: "Cardio Implant Hall", shortLabel: "Hall 1" },
  { clientId: "pad-b", hallId: "hall_02", hallName: "Cardiac Implant Hall", shortLabel: "Hall 2" },
  { clientId: "pad-c", hallId: "hall_03", hallName: "Peripheral Implant Hall", shortLabel: "Hall 3" },
  { clientId: "pad-d", hallId: "hall_04", hallName: "Neuro Implant Hall", shortLabel: "Hall 4" },
  { clientId: "pad-e", hallId: "hall_05", hallName: "Exosome & HIFU Hall", shortLabel: "Hall 5" },
  { clientId: "pad-f", hallId: "hall_06", hallName: "Ortho & Urology Hall", shortLabel: "Hall 6" },
  { clientId: "pad-g", hallId: "hall_07", hallName: "Non-interventional Product Hall", shortLabel: "Hall 7" },
  { clientId: "pad-h", hallId: "hall_08", hallName: "Medical Standard Parts Hall", shortLabel: "Hall 8" },
]);

const state = {
  mode: DEFAULT_MODE,
  clientId: "",
  display: null,
  hall: null,
  products: [],
  referencedProducts: [],
  selectedProductId: "",
  loading: true,
  errorMessage: "",
  errorDetail: "",
  online: typeof navigator === "undefined" ? true : navigator.onLine !== false,
  usingOfflineSnapshot: false,
  offlineReady: false,
  syncTone: "pending",
  syncMessage: TEXT.syncPendingInit,
  syncBusy: false,
  lastSyncedAtMs: 0,
  audioBusy: false,
  audioError: "",
  playingProductId: "",
  pendingPlaybackProductId: "",
  stationPlaybackBusy: false,
  stationPlaybackError: "",
  playingStationSlotKey: "",
  pendingStationSlotKey: "",
  stationPlaybackSlotKey: "",
  stationPlaybackStopName: "",
  stationPlaybackQueue: [],
  stationPlaybackNodes: [],
  stationPlaybackNodeIndex: -1,
  stationPlaybackNodeId: "",
  stationPlaybackMode: "idle",
  stationPlaybackRangeEndMs: null,
  stationPlaybackSegmentIndex: -1,
  stationPlaybackState: "idle",
  stationPlaybackCursorMs: 0,
  stationPlaybackTotalDurationMs: 0,
  stationPlaybackAnswerText: "",
  stationPlaybackTimelineEvents: [],
  stationPlaybackEndedHotspotIds: [],
  highlightedHotspotId: "",
  highlightedProductId: "",
  visibleHotspotIds: [],
  flashingHotspotIds: [],
  activeNarrationNodeId: "",
  stationTimelineSelections: Object.create(null),
  lastPlaybackRequestedUrl: "",
  assetBusy: false,
  assetAction: "",
  assetMessage: "",
  assetTone: "pending",
  audioTextDrafts: Object.create(null),
  productInfoDrafts: Object.create(null),
  displayProductPlayCounts: Object.create(null),
  productPlayCounts: Object.create(null),
  demoColumns: DEFAULT_DEMO_COLUMNS,
  opsShowDemoLayout: false,
  opsShowHallProductList: false,
  opsShowHallSwitcher: false,
  opsStationTab: "annotate",
  opsAnnotateSidebarTab: "overview",
  demoLeftTabKey: DEFAULT_DEMO_LEFT_TAB,
  demoRightTabKey: DEFAULT_DEMO_RIGHT_TAB,
  scenes: [],
  selectedSceneId: "",
  sceneDialogHotspotId: "",
  sceneEditorActiveHotspotId: "",
  sceneEditorDraft: null,
  sceneEditorCreateMode: false,
  hotspotSearchResults: [],
  hotspotSearchBusy: false,
  hotspotSearchQuery: "",
  demoStationSlots: [],
  recordingOptions: [],
  recordingOptionsReady: false,
  recordingOptionsError: "",
  recordingMetaById: Object.create(null),
  stationCatalog: [],
};

const refs = {
  app: document.getElementById("app"),
  audio: document.getElementById("product-audio"),
  audioStatus: document.getElementById("audio-status-text"),
};

const appContext = {
  state,
  refs,
  runtime: {
    latestLoadSeq: 0,
    latestSyncSeq: 0,
    latestHotspotSearchSeq: 0,
    latestStationPlaybackSeq: 0,
    sceneEditorInteraction: null,
    stationTimelineInteraction: null,
    narrationNodeInteraction: null,
    hotspotSearchComposing: false,
    lastFlashLogicLogKey: "",
    lastFlashRenderLogKey: "",
  },
  caches: {
    recordingMetaRequestMap: Object.create(null),
    stationSegmentDurationCache: Object.create(null),
    narrationStopDurationCache: Object.create(null),
    narrationStopDurationRequestMap: Object.create(null),
  },
};

const appActions = {
  setMode: null,
  toggleOpsSection: null,
  setDemoColumns: null,
  setDemoLeftTab: null,
  setDemoRightTab: null,
  setOpsStationTab: null,
  setOpsAnnotateSidebarTab: null,
  toggleActiveStationSlot: null,
  switchHall: null,
  loadCurrentHall: null,
  syncOfflineResources: null,
  toggleProductPlayback: null,
  playSelectedProduct: null,
  toggleStationPlayback: null,
  playStationSlot: null,
  pauseStationPlayback: null,
  resumeStationPlayback: null,
  updateStationSlot: null,
  addStationTimelineEvent: null,
  removeStationTimelineEvent: null,
  moveStationTimelineEvent: null,
  updateStationTimelineEvents: null,
  useCurrentPlaybackTimeForTimelineEvent: null,
  seekStationPlaybackToMs: null,
  deleteStationTimelineSelection: null,
  addStationNarrationNode: null,
  setActiveNarrationNode: null,
  moveStationNarrationNode: null,
  removeStationNarrationNode: null,
  updateStationNarrationNode: null,
  playNarrationNode: null,
  toggleNarrationNodeHotspotBinding: null,
  requestExit: null,
  updateSceneEditorDraft: null,
  clearHotspotProductSearch: null,
  searchStationHotspotProducts: null,
  upsertReferencedProduct: null,
  saveSelectedProductInfo: null,
  regenerateSelectedProductAudio: null,
  uploadSelectedProductAudio: null,
  uploadSelectedProductImages: null,
  saveSelectedStationConfig: null,
  uploadSelectedStationAsset: null,
  exportCurrentStationHotspots: null,
  importCurrentStationHotspots: null,
  enterStationHotspotCreateMode: null,
  saveSceneEditorHotspot: null,
  deleteSceneEditorHotspot: null,
  createSceneFromUpload: null,
  saveSelectedSceneMeta: null,
  replaceSelectedSceneBackground: null,
  deleteSelectedScene: null,
  selectSceneHotspotForEditing: null,
};

const appSelectors = {
  getShellViewModel: null,
  getHallPresetViewModels: null,
  getDemoAudienceViewModel: null,
  getSceneTabViewModels: null,
  getDemoLayoutOptionViewModels: null,
  getOpsShellViewModel: null,
  getSceneDialogViewModel: null,
  getDemoScenePanelViewModel: null,
  getFullscreenSceneViewModel: null,
};
