import { useMemo } from 'react';

export function useRightPanelTabsProps({
  showHistoryPanel,
  historySort,
  onChangeHistorySort,
  historyItems,
  onPickHistoryQuestion,
  showDebugPanel,
  debugInfo,
  qaCacheDebug,
  guideModeLabel,
  ttsEnabled,
  tourState,
  serverStatus,
  serverStatusErr,
  serverEvents,
  serverEventsErr,
  serverLastError,
  questionQueue,
  onAnswerQueuedNow,
  onRemoveQueuedQuestion,
}) {
  return useMemo(
    () => ({
      showHistoryPanel,
      historySort,
      onChangeHistorySort,
      historyItems,
      onPickHistoryQuestion,
      showDebugPanel,
      debugInfo,
      qaCacheDebug,
      guideModeLabel,
      ttsEnabled,
      tourState,
      serverStatus,
      serverStatusErr,
      serverEvents,
      serverEventsErr,
      serverLastError,
      questionQueue,
      onAnswerQueuedNow,
      onRemoveQueuedQuestion,
    }),
    [
      showHistoryPanel,
      historySort,
      onChangeHistorySort,
      historyItems,
      onPickHistoryQuestion,
      showDebugPanel,
      debugInfo,
      qaCacheDebug,
      guideModeLabel,
      ttsEnabled,
      tourState,
      serverStatus,
      serverStatusErr,
      serverEvents,
      serverEventsErr,
      serverLastError,
      questionQueue,
      onAnswerQueuedNow,
      onRemoveQueuedQuestion,
    ]
  );
}
